services:
  nginx:
    container_name: ${PROJECT_TAG}-nginx
    image: nginx:alpine
    env_file:
      - ".env"
    ports:
      - "0.0.0.0:80:80/tcp"
    configs:
      - source: nginx
        target: /etc/nginx/conf.d/default.conf
        uid: "0"
        gid: "0"
        mode: 0644
    restart: unless-stopped
    healthcheck:
      test: wget --spider --no-verbose --tries=1 http://${NGINX_HOST}:${NGINX_PORT} || exit 1
      interval: 30s
      timeout: 5s
      retries: 2

  frontend:
    container_name: ${PROJECT_TAG}-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ".env"
    ports:
      - "127.0.0.1:3000:3000/tcp"
    restart: unless-stopped
    volumes:
      - "frontend_data:/data"
    healthcheck:
      test: wget --spider --no-verbose --tries=1 http://127.0.0.1:${FRONTEND_PORT} || exit 1
      interval: 30s
      timeout: 5s
      retries: 2

  backend:
    container_name: ${PROJECT_TAG}-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ".env"
    ports:
      - "127.0.0.1:3500:3500/tcp"
    restart: unless-stopped
    volumes:
      - "backend_data:/data"
    healthcheck:
      test: wget -q -O - 127.0.0.1:${BACKEND_PORT} | grep "server work" || exit 1
      interval: 30s
      timeout: 5s
      retries: 2

  db:
    container_name: ${PROJECT_TAG}-db
    image: mariadb:lts
    env_file:
      - ".env"
    restart: unless-stopped
    volumes:
      - "mariadb_data:/var/lib/mysql"
      - "./db/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql:ro"
    ports:
      - "127.0.0.1:3306:3306/tcp"
    healthcheck:
      test: mysqladmin ping --silent -u root --password=${MARIADB_ROOT_PASSWORD} | grep -q "mysqld is alive"
      interval: 30s
      timeout: 5s
      retries: 2

volumes:
  frontend_data:
  backend_data:
  mariadb_data:

configs:
  nginx:
    file: ./nginx/default.conf
